[package]
name = "heimdallr"
version = "0.1.0"
authors = ["Matthew M. Keeler <keelerm84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
